apiVersion: v1
kind: ConfigMap
metadata:
  name: mypostgres-configmap

data:
  POSTGRES_USER: postgres
  POSTGRES_DATABASE: postgres
  POSTGRES_HOST: mypostgres-cluster-ip-service
  POSTGRES_PORT: '5432'
