apiVersion: v1
kind: Service
metadata:
  name: myfrontend-node-port-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31110
  selector:
    app: myfrontend
    component: frontend
