apiVersion: v1
kind: Service
metadata:
  name: mynginx-node-port-service

spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31000
  selector:
    component: server
    app: mynginx
