apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: myapp-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1

spec:
  rules:
    - host: myapp
      http:
        paths:
          - path: /api/(.*)
            pathType: Prefix
            backend:
              service:
                name: mybackend-cluster-ip-service
                port:
                  number: 5000
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: myfrontend-cluster-ip-service
                port:
                  number: 80
