apiVersion: v1
kind: Service
metadata:
  name: mybackend-node-port-service

spec:
  type: NodePort
  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 31100
  selector:
    app: mybackend
    component: backend
